---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: server
  namespace: xmas-trees
spec:
  template:
    spec:
      containers:
      - image: "charlieegan3/policing-christmas-trees-server:636a25c31496ddc1089d0d22511d3f37"
        ports:
        - name: http1
          containerPort: 8081
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
