apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashcards
  namespace: flashcards
spec:
  selector:
    matchLabels:
      app: flashcards
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flashcards
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "flashcards-api"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-env: "secret/flashcards-api/main"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "secret/flashcards-api/main" -}}
          {{- .Data.env -}}
          {{- end -}}
    spec:
      containers:
      - name: web
        image: "charlieegan3/flashcards:arm-6b30b4e295cf28429ef334b25b6313a863b654d8"
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: ENV_PATH
          value: /vault/secrets/env
        resources:
          limits:
            cpu: "2"
            memory: "500Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
