---
kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-template
  namespace: auth
data:
  config.hcl: |
    template {
      error_on_missing_key = true
      contents = <<EOH
        {{- with secret "secret/auth/main" -}}
        {{- .Data.text -}}
        {{- end -}}
      EOH
      destination = "/etc/oauth2_proxy/oauth2_proxy.cfg"
    }
