---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: serializer
  name: serializer
  namespace: serializer
spec:
  endpoints:
  - interval: 30s
    port: web
  namespaceSelector:
    matchNames:
    - serializer
  selector:
    matchLabels:
      app: serializer
