{{- range $_, $job :=  .Values.cronjobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $job.name }}"
  namespace: {{ include "music.name" $ }}
spec:
  # this is to prevent the controller hitting FailedNeedsStart
  # I think this is related to clock skew from my premptible VMs
  startingDeadlineSeconds: 30
  schedule: "{{ $job.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        cronjob: "{{ $job.name }}"
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/role: "music"
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-secret-env: "secret/music/main"
            vault.hashicorp.com/agent-inject-template-env: |
              {{`
              {{- with secret "secret/music/main" -}}
              {{- .Data.text -}}
              {{- end -}}
              `}}
            vault.hashicorp.com/agent-inject-secret-key.json: "secret/music/google"
            vault.hashicorp.com/agent-inject-template-key.json: |
              {{`
              {{- with secret "secret/music/google" -}}
              {{- .Data.key -}}
              {{- end -}}
              `}}
        spec:
          restartPolicy: OnFailure
          containers:
          - image: "{{ $.Values.images.tracker }}"
            name: "{{ $job.name }}"
            args:
            - /musicPlayTracker
            - "{{ $job.command }}"
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /vault/secrets/key.json
            - name: ENV_PATH
              value: /vault/secrets/env
{{- end }}
