{{- range $_, $job :=  .Values.cronjobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $job.name }}"
  namespace: {{ include "music.name" $ }}
spec:
  # this is to prevent the controller hitting FailedNeedsStart
  # I think this is related to clock skew from my premptible VMs
  startingDeadlineSeconds: 30
  schedule: "{{ $job.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        cronjob: "{{ $job.name }}"
    spec:
      template:
        spec:
          serviceAccount: music-sync
          restartPolicy: OnFailure
          volumes:
          - name: shared-data
            emptyDir:
              medium: Memory
          - name: vault-token
            emptyDir:
              medium: Memory
          - name: consul-template-config
            configMap:
              name: consul-template
          initContainers:
          - name: vault-authenticator
            image: registry.hub.docker.com/sethvargo/vault-kubernetes-authenticator:0.1.0
            volumeMounts:
            - name: vault-token
              mountPath: /home/vault
            env:
            - name: TOKEN_DEST_PATH
              value: /home/vault/.vault-token
            - name: VAULT_ADDR
              value: "http://vs-vault.vault:8200"
            - name: VAULT_ROLE
              value: music
          - name: consul-template
            image: registry.hub.docker.com/hashicorp/consul-template:0.19.5-scratch
            command:
            - /consul-template
            - -config
            - /etc/consul-template/config.hcl
            - -log-level
            - debug
            - -once
            volumeMounts:
            - mountPath: /etc/config/
              name: shared-data
            - name: vault-token
              mountPath: /home/vault
            - name: consul-template-config
              mountPath: /etc/consul-template
            env:
            - name: HOME
              value: /home/vault
            - name: VAULT_ADDR
              value: "http://vs-vault.vault:8200"
            - name: VAULT_SKIP_VERIFY
              value: "true"
          - name: fetch-google-token
            command:
            - /bin/sh
            - -c
            # sleep to wait for pod to arrive in informer cache
            - "sleep 5 && curl -H 'Metadata-Flavor: Google' http://metadata/computeMetadata/v1/instance/service-accounts/bigquery-uploader@charlieegan3-music-1.iam.gserviceaccount.com/token > /etc/config/google.json"
            image: google/cloud-sdk
            volumeMounts:
            - mountPath: /etc/config
              name: shared-data
          containers:
          - image: "{{ $.Values.images.tracker }}"
            name: "{{ $job.name }}"
            args:
            - /musicPlayTracker
            - "{{ $job.command }}"
            env:
            - name: GOOGLE_ACCESS_TOKEN_PATH
              value: /etc/config/google.json
            - name: GO_ENV
              value: prod
            volumeMounts:
            - mountPath: /etc/config
              name: shared-data
{{- end }}
