---
apiVersion: v1
kind: Service
metadata:
  name: music-summary-website
  labels:
    app: music-summary-website
  namespace: {{ include "music.name" . }}
spec:
  type: ClusterIP
  selector:
    app: music-summary-website
  ports:
    - name: http
      protocol: TCP
      port: 80
