---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
  namespace: {{ include "music.name" . }}
spec:
  selector:
    matchLabels:
      app: uploader
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: uploader
    spec:
      serviceAccount: music-sync
      volumes:
      - name: shared-data
        emptyDir:
          medium: Memory
      - name: vault-token
        emptyDir:
          medium: Memory
      - name: consul-template-config
        configMap:
          name: consul-template
      initContainers:
      - name: vault-authenticator
        image: registry.hub.docker.com/sethvargo/vault-kubernetes-authenticator:0.1.0
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        env:
        - name: TOKEN_DEST_PATH
          value: /home/vault/.vault-token
        - name: VAULT_ADDR
          value: "http://vs-vault.vault:8200"
        - name: VAULT_ROLE
          value: music
      - name: consul-template
        image: registry.hub.docker.com/hashicorp/consul-template:0.19.5-scratch
        command:
        - /consul-template
        - -config
        - /etc/consul-template/config.hcl
        - -log-level
        - debug
        - -once
        volumeMounts:
        - mountPath: /etc/config/
          name: shared-data
        - name: vault-token
          mountPath: /home/vault
        - name: consul-template-config
          mountPath: /etc/consul-template
        env:
        - name: HOME
          value: /home/vault
        - name: VAULT_ADDR
          value: "http://vs-vault.vault:8200"
        - name: VAULT_SKIP_VERIFY
          value: "true"
      containers:
      - name: uploader
        image: "{{ $.Values.images.tracker }}"
        args:
        - /musicPlayTracker
        - uploader
        env:
        - name: GO_ENV
          value: prod
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /etc/config/
          name: shared-data
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
