---
apiVersion: v1
kind: Service
metadata:
  name: uploader
  labels:
    app: uploader
  namespace: {{ include "music.name" . }}
spec:
  type: ClusterIP
  selector:
    app: uploader
  ports:
  - name: http
    protocol: TCP
    port: 8080
