---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: flashcards
  namespace: flashcards
spec:
  template:
    spec:
      volumes:
      - name: config
        secret:
          secretName: config
      containers:
      - image: charlieegan3/flashcards:2f85aa1db99f44f3cb14b8846fc1d122
        ports:
        - name: http1
          containerPort: 3000
        volumeMounts:
        - name: config
          mountPath: /etc/rails/config
        resources:
          limits:
            cpu: "2"
            memory: "500Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
