nameOverride: promop
fullNameOverride: promop

defaultRules:
  rules:
    # these have all been disabled and included manually becuase they make
    # assumptions that do not hold about metric labels from ksm
    kubernetesResources: false
    node: true
    # creating my own with the new label names
    k8s: false

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/auth-url: "https://auth.charlieegan3.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.charlieegan3.com/oauth2/start?rd=https://prometheus.charlieegan3.com"
    hosts:
    - prometheus.charlieegan3.com
    tls:
    - hosts:
      - prometheus.charlieegan3.com
      secretName: prometheus-tls
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    externalUrl: ""
    ruleSelector:
      matchLabels: {}
    retention: 6h
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 1
    image:
      tag: v2.14.0
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
    additionalScrapeConfigsExternal: true

alertmanager:
  alertmanagerSpec:
    useExistingSecret: true
    externalUrl: https://alertmanager.charlieegan3.com
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/auth-url: "https://auth.charlieegan3.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.charlieegan3.com/oauth2/start?rd=https://alertmanager.charlieegan3.com"
    hosts:
    - alertmanager.charlieegan3.com
    tls:
    - hosts:
      - alertmanager.charlieegan3.com
      secretName: alertmanager-tls

prometheusOperator:
  kubeletService:
    namespace: monitoring
kubelet:
  # deploy my own service monitor to drop labels
  enabled: false

kubeDns:
  enabled: true
  service:
    selector:
      k8s-app: kube-dns

grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubeStateMetrics:
  enabled: false
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
coreDns:
  enabled: false
