global:
  defaultResources:
    requests:
      cpu: 10m
      memory: 10Mi
  proxy:
    resources:
      requests:
        cpu: 10m
        memory: 10Mi

pilot:
  autoscaleMin: 1
  autoscaleMax: 1
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
  enabled: false

mixer:
  policy:
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
  telemetry:
    enabled: false

gateways:
  istio-ingressgateway:
    type: ClusterIP
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
    ports: # these have had the node ports and bonus ports disabled
    - port: 15020
      targetPort: 15020
      name: status-port
    - port: 80
      targetPort: 80
      name: http2
      # nodePort: 31380
    - port: 443
      name: https
      # nodePort: 31390
   #- port: 31400
   #  name: tcp
   #  # nodePort: 31400
   #- port: 15029
   #  targetPort: 15029
   #  name: https-kiali
   #- port: 15030
   #  targetPort: 15030
   #  name: https-prometheus
   #- port: 15031
   #  targetPort: 15031
   #  name: https-grafana
   #- port: 15032
   #  targetPort: 15032
   #  name: https-tracing
   #- port: 15443
   #  targetPort: 15443
   #  name: tls
