global:
  defaultPodDisruptionBudget:
    enabled: false
  defaultResources:
    requests:
      cpu: 10m
      memory: 10Mi
  proxy:
    resources:
      requests:
        cpu: 10m
        memory: 10Mi

kiali:
  enabled: true
  createDemoSecret: true
  prometheusAddr: http://po-promop-prometheus.monitoring:9090
  contextPath: "/" # path ui and ingress
  ingress:
    enabled: true
    hosts:
    - kiali.charlieegan3.com
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-url: "https://auth.charlieegan3.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.charlieegan3.com/oauth2/start?rd=https://kiali.charlieegan3.com"
    tls:
    - secretName: kiali-tls
      hosts:
      - kiali.charlieegan3.com

pilot:
  autoscaleMin: 1
  autoscaleMax: 1
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
  enabled: false

mixer:
  policy:
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
  telemetry:
    enabled: true

gateways:
  istio-ingressgateway:
    type: ClusterIP
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
    ports: # these have had the node ports and bonus ports disabled
    - port: 15020
      targetPort: 15020
      name: status-port
    - port: 80
      targetPort: 80
      name: http2
      # nodePort: 31380
    - port: 443
      name: https
      # nodePort: 31390
   #- port: 31400
   #  name: tcp
   #  # nodePort: 31400
   #- port: 15029
   #  targetPort: 15029
   #  name: https-kiali
   #- port: 15030
   #  targetPort: 15030
   #  name: https-prometheus
   #- port: 15031
   #  targetPort: 15031
   #  name: https-grafana
   #- port: 15032
   #  targetPort: 15032
   #  name: https-tracing
   #- port: 15443
   #  targetPort: 15443
   #  name: tls
