---
kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-template
  namespace: airtable-spaced-repetition
data:
  config.hcl: |
    template {
      error_on_missing_key = true
      contents = <<EOH
        {{- with secret "secret/airtable-spaced-repetition/main" -}}
        {{- .Data.text -}}
        {{- end -}}
      EOH
      destination = "/etc/config/env"
    }
