---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reminder
  namespace: airtable-spaced-repetition
spec:
  schedule: "0 6 1-31/2 * *"
  jobTemplate:
    metadata:
      labels:
        cronjob: reminder
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: secrets
            emptyDir:
              medium: Memory
          - name: vault-token
            emptyDir:
              medium: Memory
          - name: consul-template-config
            configMap:
              name: consul-template
          initContainers:
          - name: vault-authenticator
            image: registry.hub.docker.com/sethvargo/vault-kubernetes-authenticator:0.1.0
            volumeMounts:
            - name: vault-token
              mountPath: /home/vault
            env:
            - name: TOKEN_DEST_PATH
              value: /home/vault/.vault-token
            - name: VAULT_ADDR
              value: "http://vs-vault.vault:8200"
            - name: VAULT_ROLE
              value: airtable-spaced-repetition
          - name: consul-template
            image: registry.hub.docker.com/hashicorp/consul-template:0.19.5-scratch
            command:
            - /consul-template
            - -config
            - /etc/consul-template/config.hcl
            - -log-level
            - debug
            - -once
            volumeMounts:
            - name: secrets
              mountPath: /etc/config
            - name: vault-token
              mountPath: /home/vault
            - name: consul-template-config
              mountPath: /etc/consul-template
            env:
            - name: HOME
              value: /home/vault
            - name: VAULT_ADDR
              value: "http://vs-vault.vault:8200"
            - name: VAULT_SKIP_VERIFY
              value: "true"
          containers:
          - name: reminder
            image: charlieegan3/airtable-spaced-repetition:86c6f8fd496c12aa2ef6943b04c404eb
            volumeMounts:
            - name: secrets
              mountPath: /etc/config
