---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: personal-website
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: clockify
---
apiVersion: v1
kind: Namespace
metadata:
  name: calendars
---
apiVersion: v1
kind: Namespace
metadata:
  name: mycriticmatch
---
apiVersion: v1
kind: Namespace
metadata:
  name: rssmerge
---
apiVersion: v1
kind: Namespace
metadata:
  name: xmas-trees
---
apiVersion: v1
kind: Namespace
metadata:
  name: borked
---
apiVersion: v1
kind: Namespace
metadata:
  name: music
---
apiVersion: v1
kind: Namespace
metadata:
  name: photos
---
apiVersion: v1
kind: Namespace
metadata:
  name: boot
---
apiVersion: v1
kind: Namespace
metadata:
  name: flashcards
---
apiVersion: v1
kind: Namespace
metadata:
  name: speedtest-exporter
---
apiVersion: v1
kind: Namespace
metadata:
  name: edgemax-exporter
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: simple-proxy
