---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ksm-kube-state-metrics
  namespace: monitoring
spec:
  endpoints:
  - port: http
    honorLabels: true
    metricRelabelings:
    - sourceLabels:
      - "__name__"
      # kubectl get prometheus rules -o yaml cat out.yaml | grep -o "kube_\w*" | sort | uniq
      regex: "(kube_cronjob_next_schedule_time|kube_daemonset_status_current_number_scheduled|kube_daemonset_status_desired_number_scheduled|kube_daemonset_status_number_misscheduled|kube_daemonset_status_number_ready|kube_deployment_metadata_generation|kube_deployment_spec_replicas|kube_deployment_status_observed_generation|kube_deployment_status_replicas_available|kube_job_failed|kube_job_labels|kube_job_spec_completions|kube_job_status_failed|kube_job_status_start_time|kube_job_status_succeeded|kube_node_status_condition|kube_persistentvolume_status_phase|kube_pod_container_resource_requests_cpu_cores|kube_pod_container_resource_requests_memory_bytes|kube_pod_container_status_restarts_total|kube_pod_info|kube_pod_info_node_count|kube_pod_labels|kube_pod_owner|kube_pod_status_phase|kube_replicaset_owner|kube_resourcequota|kube_statefulset_metadata_generation|kube_statefulset_replicas|kube_statefulset_status_current_revision|kube_statefulset_status_observed_generation|kube_statefulset_status_replicas|kube_statefulset_status_replicas_ready|kube_statefulset_status_replicas_updated|kube_statefulset_status_update_revision)"
      action: keep
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
