---
kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-template
  namespace: {{ include "personal-website.name" $ }}
data:
  config.hcl: |
    {{`
    template {
      error_on_missing_key = true
      contents = <<EOH
        {{- with secret "secret/personal-website/main" -}}
    {{ .Data.text -}}
        {{- end -}}
      EOH
      destination = "/etc/config/env"
    }`}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "personal-website.name" $ }}
  labels:
    app: {{ include "personal-website.name" $ }}
  namespace: {{ include "personal-website.name" $ }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "personal-website.name" $ }}
  template:
    metadata:
      labels:
        app: {{ include "personal-website.name" $ }}
    spec:
      volumes:
      - name: shared-app-dir
        emptyDir: {}
      - name: secrets
        emptyDir:
          medium: Memory
      - name: vault-token
        emptyDir:
          medium: Memory
      - name: consul-template-config
        configMap:
          name: consul-template
      initContainers:
      - name: vault-authenticator
        image: registry.hub.docker.com/sethvargo/vault-kubernetes-authenticator:0.1.0
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        env:
        - name: TOKEN_DEST_PATH
          value: /home/vault/.vault-token
        - name: VAULT_ADDR
          value: "http://vs-vault.vault:8200"
        - name: VAULT_ROLE
          value: personal-website
      - name: consul-template
        image: registry.hub.docker.com/hashicorp/consul-template:0.19.5-scratch
        command:
        - /consul-template
        - -config
        - /etc/consul-template/config.hcl
        - -log-level
        - debug
        - -once
        volumeMounts:
        - mountPath: /etc/config/
          name: secrets
        - name: vault-token
          mountPath: /home/vault
        - name: consul-template-config
          mountPath: /etc/consul-template
        env:
        - name: HOME
          value: /home/vault
        - name: VAULT_ADDR
          value: "http://vs-vault.vault:8200"
        - name: VAULT_SKIP_VERIFY
          value: "true"
      - name: volume-init
        image: {{ .Values.images.web }}
        command:
        - sh
        - -c
        - "mv /usr/share/nginx/html/* /shared"
        volumeMounts:
        - mountPath: /shared
          name: shared-app-dir
      containers:
      - name: json-reloader
        image: {{ .Values.images.json }}
        command:
        - /statusUpdater
        - --refresh=true
        - --repeat=true
        - --interval=600
        - --output=/shared/status.json
        resources:
          limits:
            cpu: "200m"
            memory: "50Mi"
          requests:
            cpu: "50m"
            memory: "50Mi"
        volumeMounts:
        - mountPath: /shared
          name: shared-app-dir
        - mountPath: /etc/config/
          name: secrets
        env:
        - name: GO_ENV
          value: prod
      - name: web
        image: {{ .Values.images.web }}
        ports:
        - name: web
          containerPort: 80
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: shared-app-dir
