---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: serializer
  name: serializer
  namespace: {{ include "serializer.name" $ }}
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
    protocol: TCP
  selector:
    app: serializer
  sessionAffinity: None
  type: ClusterIP
