apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kubeip
  name: kubeip-config
  namespace: kube-system
data:
  KUBEIP_LABELKEY: "kubeip"
  KUBEIP_LABELVALUE: "main"
  KUBEIP_NODEPOOL: "ingress"
  KUBEIP_FORCEASSIGNMENT: "true"
