apiVersion: v1
kind: Service
metadata:
  name: exporter
  namespace: speedtest-exporter
  labels:
    app: exporter
spec:
  type: ClusterIP
  selector:
    app: exporter
  ports:
  - name: metrics
    protocol: TCP
    port: 9112
    targetPort: metrics
