---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-cronjob-status
  namespace: monitoring
spec:
  groups:
  - name: kube-cron
    rules:
    - record: job_cronjob:kube_job_status_start_time:max
      expr: |
        label_replace(
          label_replace(
            max(
              kube_job_status_start_time
              * ON(job_name) GROUP_RIGHT()
              kube_job_labels{label_cronjob!=""}
            ) BY (job_name, label_cronjob)
            == ON(label_cronjob) GROUP_LEFT()
            max(
              kube_job_status_start_time
              * ON(job_name) GROUP_RIGHT()
              kube_job_labels{label_cronjob!=""}
            ) BY (label_cronjob),
            "job", "$1", "job_name", "(.+)"),
            "cronjob", "$1", "label_cronjob", "(.+)")
    - record: job_cronjob:kube_job_status_failed:sum
      expr: |
        clamp_max(
          job_cronjob:kube_job_status_start_time:max,
        1)
        * ON(job_name) GROUP_LEFT()
        label_replace(
          sum(kube_job_failed) by (job_name)
          *
          ON(job_name) GROUP_RIGHT()
            kube_job_labels{label_cronjob!=""},
          "cronjob", "$1", "label_cronjob", "(.*)")
    - alert: CronJobStatusFailed
      expr: |
        sum(job_cronjob:kube_job_status_failed:sum) by (label_cronjob) > 0
      for: 3h
      annotations:
        description: '{{ $labels.label_cronjob }} last run has failed {{ $value }} times.'
