---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-high-request-rate
  namespace: monitoring
spec:
  groups:
  - name: web-apps
    rules:
    - alert: HighRequestRate
      expr: |
        avg(rate(http_server_requests_total[1m])) by (job) > 0.2
      for: 5m
      annotations:
        description: '{{ $labels.job }} is getting {{ $value }} high traffic.'
