---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: alertmanager-config-creator
  namespace: monitoring
spec:
  concurrencyPolicy: Forbid
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        cronjob: alertmanager-config-creator
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/role: "monitoring"
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-secret-alertmanager.yaml: "secret/monitoring/alertmanager-config"
            vault.hashicorp.com/agent-inject-template-alertmanager.yaml: |
              {{- with secret "secret/monitoring/alertmanager-config" -}}
              {{- .Data.text -}}
              {{- end -}}
        spec:
          restartPolicy: Never
          serviceAccount: alertmanager-config-creator
          containers:
          - name: create-config-map
            image: gcr.io/google_containers/hyperkube:v1.15.5
            command:
            - /bin/sh
            - -c
            - |-
              kubectl create secret generic alertmanager-po-promop-alertmanager \
                --from-file=/vault/secrets/alertmanager.yaml \
                -n monitoring \
                -o yaml \
                --dry-run > secret.yaml && \
              kubectl apply -f secret.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-config-creator
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-creator
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-secrets
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: alertmanager-config-creator
  namespace: monitoring
roleRef:
  kind: Role
  name: configmap-creator
  apiGroup: rbac.authorization.k8s.io
