apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: po-promop-k8s.rules
  namespace: monitoring
spec:
  groups:
  - name: k8s.rules
    rules:
    - expr: sum(rate(container_cpu_usage_seconds_total{job="kubelet", image!="", container_name!=""}[5m]))
        by (namespace)
      record: namespace:container_cpu_usage_seconds_total:sum_rate
    - expr: |-
        sum by (namespace, pod_name, container_name) (
          rate(container_cpu_usage_seconds_total{job="kubelet", image!="", container_name!=""}[5m])
        )
      record: namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate
    - expr: sum(container_memory_usage_bytes{job="kubelet", image!="", container_name!=""})
        by (namespace)
      record: namespace:container_memory_usage_bytes:sum
    - expr: |-
        sum by(namespace, label_name)
        (
          sum by(namespace, pod) (
            rate(container_cpu_usage_seconds_total{container_name!="",image!="",job="kubelet"}[5m])
          ) * on(namespace, pod)
          group_left(label_name)
          kube_pod_labels{job="kube-state-metrics"}
        )
      # this has been fixed to not use relabeling
      record: namespace_name:container_cpu_usage_seconds_total:sum_rate
    - expr: |-
        sum by(namespace, label_name) (
            sum by(pod_name, namespace) (
                container_memory_usage_bytes{container_name!="",image!="",job="kubelet"}
            )
            * on(namespace, pod_name) group_left(label_name)
            label_replace(
                label_replace(
                    kube_pod_labels{job="kube-state-metrics"},
                    "pod_name", "$1", "exported_pod", "(.*)"
                ),
                "namespace", "$1", "exported_namespace", "(.*)"
            )
        )
      record: namespace_name:container_memory_usage_bytes:sum
    - expr: |-
        sum by(namespace, label_name) (
            sum by(namespace, pod) (
                label_replace(
                    label_replace(
                        kube_pod_container_resource_requests_memory_bytes{job="kube-state-metrics"},
                        "pod", "$1", "exported_pod", "(.*)"
                    ),
                    "namespace", "$1", "exported_namespace", "(.*)"
                )
                * on(endpoint, instance, job, namespace, pod, service)
                group_left(phase) (
                    label_replace(
                        label_replace(
                            kube_pod_status_phase{phase=~"^(Pending|Running)$"} == 1,
                            "pod", "$1", "exported_pod", "(.*)"
                        ),
                        "namespace", "$1", "exported_namespace", "(.*)"
                    )
                )
            )
            * on(namespace, pod)
            group_left(label_name)
            label_replace(
                label_replace(
                    kube_pod_labels{job="kube-state-metrics"},
                    "pod", "$1", "exported_pod", "(.*)"
                ),
                "namespace", "$1", "exported_namespace", "(.*)"
            )
        )
      record: namespace_name:kube_pod_container_resource_requests_memory_bytes:sum
    - expr: |-
        sum by(namespace, label_name) (
            sum by(namespace, pod) (
                label_replace(
                    label_replace(
                        kube_pod_container_resource_requests_cpu_cores{job="kube-state-metrics"},
                        "pod", "$1", "exported_pod", "(.*)"
                    ),
                    "namespace", "$1", "exported_namespace", "(.*)"
                )
                * on(endpoint, instance, job, namespace, pod, service)
                group_left(phase) (
                    label_replace(
                        label_replace(
                            kube_pod_status_phase{phase=~"^(Pending|Running)$"} == 1,
                            "pod", "$1", "exported_pod", "(.*)"
                        ),
                        "namespace", "$1", "exported_namespace", "(.*)"
                    )
                )
            ) * on(namespace, pod)
            group_left(label_name)
            label_replace(
                label_replace(
                    kube_pod_labels{job="kube-state-metrics"},
                    "pod", "$1", "exported_pod", "(.*)"
                ),
                "namespace", "$1", "exported_namespace", "(.*)"
            )
        )
      record: namespace_name:kube_pod_container_resource_requests_cpu_cores:sum
    - expr: |-
        sum(
          label_replace(
            label_replace(
              kube_pod_owner{job="kube-state-metrics", owner_kind="ReplicaSet"},
              "replicaset", "$1", "owner_name", "(.*)"
            ) * on(replicaset, namespace) group_left(owner_name) kube_replicaset_owner{job="kube-state-metrics"},
            "workload", "$1", "owner_name", "(.*)"
          )
        ) by (exported_namespace, workload, exported_pod)
      labels:
        workload_type: deployment
      record: mixin_pod_workload
    - expr: |-
        sum(
          label_replace(
            kube_pod_owner{job="kube-state-metrics", owner_kind="DaemonSet"},
            "workload", "$1", "owner_name", "(.*)"
          )
        ) by (exported_namespace, workload, exported_pod)
      labels:
        workload_type: daemonset
      record: mixin_pod_workload
    - expr: |-
        sum(
          label_replace(
            kube_pod_owner{job="kube-state-metrics", owner_kind="StatefulSet"},
            "workload", "$1", "owner_name", "(.*)"
          )
        ) by (exported_namespace, workload, exported_pod)
      labels:
        workload_type: statefulset
      record: mixin_pod_workload
