---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: po-promop-prometheus
  namespace: monitoring
  labels:
    app: promop-prometheus
  annotations:
    iam.gke.io/gcp-service-account: thanos@charlieegan3-cluster.iam.gserviceaccount.com
