{
 "title": "GKE Costs",
 "description": "Breakdown of costs incurred by GKE workloads",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "charlieegan3-cluster,example-project"
   },
   {
    "name": "cluster_location",
    "label": "Location",
    "query": "SELECT DISTINCT cluster_location FROM `charlieegan3-cluster.cluster_usage.gke_cluster_resource_usage` "
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": "SELECT DISTINCT cluster_name FROM `charlieegan3-cluster.cluster_usage.gke_cluster_resource_usage` "
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "SELECT DISTINCT namespace FROM `charlieegan3-cluster.cluster_usage.gke_cluster_resource_usage`"
   },
   {
    "name": "app",
    "label": "App",
    "query": "SELECT DISTINCT   COALESCE(     (SELECT value      FROM UNNEST(labels)      WHERE        key = \"app\" OR key = \"app.kubernetes.io/name\" OR key = \"serving.knative.dev/service\"      ORDER BY LENGTH(value)      LIMIT 1     ), \"Unknown\"   ) AS app FROM   `charlieegan3-cluster.cluster_usage.gke_cluster_resource_usage` AS resource_usage WHERE   not namespace in (\"kube-system\", \"kube:system-overhead\")   AND REGEXP_CONTAINS(namespace, r\"^${namespace:regex}$\") ORDER BY   app = \"Unknown\", app "
   },
   {
    "name": "resource_name",
    "label": "Resource",
    "query": "SELECT DISTINCT resource_name FROM `charlieegan3-cluster.cluster_usage.gke_cluster_resource_usage` "
   }
  ]
 },
 "panels": [
  {
   "title": "Cost Per Day",
   "type": "graph",
   "description": "Cost per day for selected parameters",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(MAX(resource_usage.end_time), DAY) AS time,\n  SUM(resource_usage.usage.amount * gcp_billing_export.rate) AS cost\nFROM\n  `${project:regex}.cluster_usage.gke_cluster_resource_usage` AS resource_usage\nLEFT JOIN (\n  SELECT\n    sku.id AS sku_id,\n    SUM(cost) / SUM(usage.amount) AS rate,\n    MIN(usage_start_time) AS min_usage_start_time,\n    MAX(usage_end_time) AS max_usage_end_time\n  FROM\n    `charlieegan3-cluster.cluster_usage.billing_export3`\n  WHERE\n    project.id = \"${project:regex}\"\n    AND $__timeFilter(usage_end_time)\n  GROUP BY\n    sku_id) AS gcp_billing_export\nON\n  resource_usage.sku_id = gcp_billing_export.sku_id\nWHERE\n   resource_usage.start_time >= gcp_billing_export.min_usage_start_time\n  AND resource_usage.end_time <= gcp_billing_export.max_usage_end_time\n  AND REGEXP_CONTAINS(cluster_location, r\"^${cluster_location:regex}$\")\n  AND REGEXP_CONTAINS(cluster_name, r\"^${cluster_name:regex}$\")\n  AND REGEXP_CONTAINS(namespace, r\"^${namespace:regex}$\")\n  AND REGEXP_CONTAINS(resource_name, r\"^${resource_name:regex}$\")\n  AND REGEXP_CONTAINS(\n    COALESCE(\n      (SELECT value\n       FROM UNNEST(labels)\n       WHERE\n         key = \"app\" OR key = \"app.kubernetes.io/name\" OR key = \"serving.knative.dev/service\"\n       ORDER BY LENGTH(value)\n       LIMIT 1\n      ), \"Unknown\"\n    ), r\"^${app:regex}$\")\nGROUP BY\n  TIMESTAMP_TRUNC(resource_usage.end_time, DAY)\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Namespace Cost",
   "type": "table",
   "description": "Total cost per namespace over current time range",
   "gridPos": { "h": 25, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  namespace,\n  SUM(resource_usage.usage.amount * gcp_billing_export.rate) AS cost\nFROM\n  `charlieegan3-cluster.cluster_usage.gke_cluster_resource_usage` AS resource_usage\nLEFT JOIN (\n  SELECT\n    sku.id AS sku_id,\n    SUM(cost) / SUM(usage.amount) AS rate,\n    MIN(usage_start_time) AS min_usage_start_time,\n    MAX(usage_end_time) AS max_usage_end_time\n  FROM\n    `charlieegan3-cluster.cluster_usage.billing_export3`\n  WHERE\n    project.id = \"charlieegan3-cluster\"\n    AND $__timeFilter(usage_end_time)\n  GROUP BY\n    sku_id) AS gcp_billing_export\nON\n  resource_usage.sku_id = gcp_billing_export.sku_id\nWHERE\n  resource_usage.start_time >= gcp_billing_export.min_usage_start_time\n  AND resource_usage.end_time <= gcp_billing_export.max_usage_end_time\n  AND REGEXP_CONTAINS(cluster_location, r\"^${cluster_location:regex}$\")\n  AND REGEXP_CONTAINS(cluster_name, r\"^${cluster_name:regex}$\")\n  AND REGEXP_CONTAINS(namespace, r\"^${namespace:regex}$\")\n  AND REGEXP_CONTAINS(resource_name, r\"^${resource_name:regex}$\")\n  AND REGEXP_CONTAINS(\n    COALESCE(\n      (SELECT value\n       FROM UNNEST(labels)\n       WHERE\n         key = \"app\" OR key = \"app.kubernetes.io/name\" OR key = \"serving.knative.dev/service\"\n       ORDER BY LENGTH(value)\n       LIMIT 1\n      ), \"Unknown\"\n    ), r\"^${app:regex}$\")\nGROUP BY namespace\nORDER BY\n  REGEXP_CONTAINS(namespace, r\"kube.system\"),\n  cost desc\n\n\n"
    }
   ]
  },
  {
   "title": "App Cost",
   "type": "table",
   "description": "Total cost per app over current time range",
   "gridPos": { "h": 25, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(\n    (SELECT value\n     FROM UNNEST(labels)\n     WHERE\n       key = \"app\" OR key = \"app.kubernetes.io/name\" OR key = \"serving.knative.dev/service\"\n     ORDER BY LENGTH(value)\n     LIMIT 1\n    ), \"Unknown\"\n  ) AS app,\n  SUM(resource_usage.usage.amount * gcp_billing_export.rate) AS cost\nFROM\n  `charlieegan3-cluster.cluster_usage.gke_cluster_resource_usage` AS resource_usage\nLEFT JOIN (\n  SELECT\n    sku.id AS sku_id,\n    SUM(cost) / SUM(usage.amount) AS rate,\n    MIN(usage_start_time) AS min_usage_start_time,\n    MAX(usage_end_time) AS max_usage_end_time\n  FROM\n    `charlieegan3-cluster.cluster_usage.billing_export3`\n  WHERE\n    project.id = \"charlieegan3-cluster\"\n    AND $__timeFilter(usage_end_time)\n  GROUP BY\n    sku_id) AS gcp_billing_export\nON\n  resource_usage.sku_id = gcp_billing_export.sku_id\nWHERE\n  resource_usage.start_time >= gcp_billing_export.min_usage_start_time\n  AND resource_usage.end_time <= gcp_billing_export.max_usage_end_time\n  AND REGEXP_CONTAINS(cluster_location, r\"^${cluster_location:regex}$\")\n  AND REGEXP_CONTAINS(cluster_name, r\"^${cluster_name:regex}$\")\n  AND REGEXP_CONTAINS(namespace, r\"^${namespace:regex}$\")\n  AND REGEXP_CONTAINS(resource_name, r\"^${resource_name:regex}$\")\n  AND REGEXP_CONTAINS(\n    COALESCE(\n      (SELECT value\n       FROM UNNEST(labels)\n       WHERE\n         key = \"app\" OR key = \"app.kubernetes.io/name\" OR key = \"serving.knative.dev/service\"\n       ORDER BY LENGTH(value)\n       LIMIT 1\n      ), \"Unknown\"\n    ), r\"^${app:regex}$\")\nGROUP BY app\nORDER BY\n  app = \"Unknown\",\n  cost desc\n"
    }
   ]
  }
 ]
}