{
 "title": "Kubernetes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "req"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "lim"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "req"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "lim"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(kube_pod_status_phase{phase=\"Pending\"}) by (pod) > 0)"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\"}[5m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "reqs"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores)",
     "legendFormat": "limits"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "allocatable"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace!=\"kube-system\"}[5m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace!=\"kube-system\"})",
     "legendFormat": "reqs"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace!=\"kube-system\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "allocatable"
    }
   ]
  }
 ]
}