---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  labels:
    grafana_datasource: "1"
  namespace: monitoring
data:
  datasource-loki.yaml: |-
    apiVersion: 1
    deleteDatasources:
    - name: Loki
      orgId: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
