---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: service
    path: "/metrics"
