---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stackdriver-exporter
  namespace: monitoring
  annotations:
    iam.gke.io/gcp-service-account: stackdriver-exporter@charlieegan3-cluster.iam.gserviceaccount.com
