kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-template
  namespace: calendars
data:
  config.hcl: |
    template {
      error_on_missing_key = true
      contents = <<EOH
        {{- with secret "secret/calendars/main" -}}
        {{- .Data.url -}}
        {{- end -}}
      EOH
      destination = "/etc/secrets/url"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendars
  namespace: calendars
spec:
  selector:
    matchLabels:
      app: calendars
  template:
    metadata:
      labels:
        app: calendars
    spec:
      volumes:
      - name: secrets
        emptyDir:
          medium: Memory
      - name: vault-token
        emptyDir:
          medium: Memory
      - name: consul-template-config
        configMap:
          name: consul-template
      initContainers:
      - name: vault-authenticator
        image: registry.hub.docker.com/sethvargo/vault-kubernetes-authenticator:0.1.0
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        env:
        - name: TOKEN_DEST_PATH
          value: /home/vault/.vault-token
        - name: VAULT_ADDR
          value: "http://vs-vault.vault:8200"
        - name: VAULT_ROLE
          value: calendars
      - name: consul-template
        image: registry.hub.docker.com/hashicorp/consul-template:0.19.5-scratch
        command:
        - /consul-template
        - -config
        - /etc/consul-template/config.hcl
        - -log-level
        - debug
        - -once
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
        - name: vault-token
          mountPath: /home/vault
        - name: consul-template-config
          mountPath: /etc/consul-template
        env:
        - name: HOME
          value: /home/vault
        - name: VAULT_ADDR
          value: "http://vs-vault.vault:8200"
        - name: VAULT_SKIP_VERIFY
          value: "true"
      containers:
      - name: calendars
        image: charlieegan3/calendars:82138f774221d8f9cae1c3e95419dc38
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
        env:
        - name: CALENDAR_URL_PATH
          value: /etc/secrets/url
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        livenessProbe:
          httpGet:
            port: http
            path: /
          initialDelaySeconds: 5
          periodSeconds: 180
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "50Mi"
            cpu: "200m"
