---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: calendars
  namespace: calendars
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "calendars"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-url: "secret/calendars/main"
        vault.hashicorp.com/agent-inject-template-url: |
          {{- with secret "secret/calendars/main" -}}
          {{- .Data.url -}}
          {{- end -}}
    spec:
      containers:
      - image: "docker.io/charlieegan3/calendars:293d5e00af617205451a44b154bbe9ea"
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: CALENDAR_URL_PATH
          value: /vault/secrets/url
        resources:
          limits:
            cpu: "20m"
            memory: "20Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
