---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: borked
  namespace: borked
spec:
  template:
    spec:
      containers:
      - image: "docker.io/charlieegan3/borked:210c4c20eb6a5d20c0c45d2cced7d60b"
        ports:
        - name: http1
          containerPort: 3000
        resources:
          limits:
            cpu: "50m"
          requests:
            cpu: "50m"
