apiVersion: v1
kind: Namespace
metadata:
  name: gke-preemptible-killer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-preemptible-killer
  namespace: gke-preemptible-killer
  labels:
    app: gke-preemptible-killer
  annotations:
    iam.gke.io/gcp-service-account: gke-preemptible-killer@charlieegan3-cluster.iam.gserviceaccount.com
---
apiVersion: v1
kind: Service
metadata:
  name: gke-preemptible-killer
  namespace: gke-preemptible-killer
  labels:
    app: gke-preemptible-killer
spec:
  type: ClusterIP
  selector:
    app: gke-preemptible-killer
  ports:
  - name: metrics
    port: 9001
    targetPort: 9001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gke-preemptible-killer
  namespace: gke-preemptible-killer
  labels:
    app: gke-preemptible-killer
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gke-preemptible-killer
  template:
    metadata:
      labels:
        app: gke-preemptible-killer
        version: 1.0.35
    spec:
      serviceAccount: gke-preemptible-killer
      terminationGracePeriodSeconds: 300
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: In
                values:
                - "true"
      containers:
      - name: gke-preemptible-killer
        image: estafette/estafette-gke-preemptible-killer:1.1.2
        ports:
        - name: prom-metrics
          containerPort: 9001
        env:
        - name: DRAIN_TIMEOUT
          value: "300"
        - name: INTERVAL
          value: "600"
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 200m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: prom-metrics
          initialDelaySeconds: 30
          timeoutSeconds: 1
