---
kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-template
  namespace: instagram-archive
data:
  config.hcl: |
    template {
      error_on_missing_key = true
      contents = <<EOH
        {{- with secret "secret/instagram-archive/main" -}}
        {{- .Data.text -}}
        {{- end -}}
      EOH
      destination = "/etc/config/env"
    }
