{
 "title": "Network",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "pppoe",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(edgemax_interfaces_received_bytes{name=\"pppoe0\"}[5m])) by (service)",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(edgemax_interfaces_transmitted_bytes{name=\"pppoe0\"}[5m])) by (service)",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "speedtest",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(speedtest_download[5m])",
     "legendFormat": "download"
    },
    {
     "expr": "avg_over_time(speedtest_upload[5m])",
     "legendFormat": "upload"
    },
    {
     "expr": "avg_over_time(speedtest_ping[5m])",
     "legendFormat": "ping"
    }
   ]
  },
  {
   "title": "edgemax",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(avg_over_time(edgemax_system_cpu_percent[10m]))",
     "legendFormat": "cpu"
    },
    {
     "expr": "max(avg_over_time(edgemax_system_memory_percent[10m]))",
     "legendFormat": "memory"
    }
   ]
  }
 ]
}