---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendars
  namespace: calendars
spec:
  selector:
    matchLabels:
      app: calendars
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "calendars"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-url: "secret/calendars/main"
        vault.hashicorp.com/agent-inject-template-url: |
          {{- with secret "secret/calendars/main" -}}
          {{- .Data.url -}}
          {{- end -}}
      labels:
        app: calendars
    spec:
      containers:
      - name: calendars
        image: "charlieegan3/calendars:arm-188c85d9621401316a5152848cd830fb"
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: CALENDAR_URL_PATH
          value: /vault/secrets/url
        resources:
          limits:
            cpu: "20m"
            memory: "20Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
