kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-template
  namespace: clockify
data:
  config.hcl: |
    template {
      error_on_missing_key = true
      contents = <<EOH
        {{ with secret "secret/clockify/main" -}}
        export API_KEY={{ .Data.api_key }}
        export USER={{ .Data.user }}
        export WORKSPACE={{ .Data.workplace }}
        {{ end }}
      EOH
      destination = "/etc/secrets/env"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clockify
  labels:
    app: clockify
  namespace: clockify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clockify
  template:
    metadata:
      labels:
        app: clockify
    spec:
      volumes:
      - name: html-dir
        emptyDir: {}
      - name: secrets
        emptyDir:
          medium: Memory
      - name: vault-token
        emptyDir:
          medium: Memory
      - name: consul-template-config
        configMap:
          name: consul-template
      initContainers:
      - name: vault-authenticator
        image: registry.hub.docker.com/sethvargo/vault-kubernetes-authenticator:0.1.0
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        env:
        - name: TOKEN_DEST_PATH
          value: /home/vault/.vault-token
        - name: VAULT_ADDR
          value: "http://vs-vault.vault:8200"
        - name: VAULT_ROLE
          value: clockify
      - name: consul-template
        image: registry.hub.docker.com/hashicorp/consul-template:0.19.5-scratch
        command:
        - /consul-template
        - -config
        - /etc/consul-template/config.hcl
        - -log-level
        - debug
        - -once
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
        - name: vault-token
          mountPath: /home/vault
        - name: consul-template-config
          mountPath: /etc/consul-template
        env:
        - name: HOME
          value: /home/vault
        - name: VAULT_ADDR
          value: "http://vs-vault.vault:8200"
        - name: VAULT_SKIP_VERIFY
          value: "true"
      - image: "charlieegan3/clockify:2e82b570ebbfaa1e0f08ee266ff5783c"
        name: set-env
        command:
        - /bin/sh
        - -c
        - "source /etc/secrets/env && envsubst < /data/index.html > /output/index.html"
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
        - mountPath: /output
          name: html-dir
      containers:
      - name: web
        image: nginx:1.13-alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-dir
        resources:
          limits:
            cpu: "50m"
            memory: "20Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
