apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: simple-proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "simple-proxy"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-token: "secret/simple-proxy/token"
        vault.hashicorp.com/agent-inject-template-token: |
          {{- with secret "secret/simple-proxy/token" -}}
          {{- .Data.text -}}
          {{- end -}}
    spec:
      containers:
      - image: "charlieegan3/simple-proxy:arm-e07a4dd442e7972bb34acf5e1d5067678eac186a"
        name: proxy
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: TOKEN_PATH
          value: /vault/secrets/token
        resources:
          limits:
            cpu: "20m"
            memory: "20Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"


