apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@charlieegan3.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
