---
kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-template
  namespace: finance
data:
  config.hcl: |
    template {
      error_on_missing_key = true
      contents = <<EOH
        {{- with secret "secret/finance/main" -}}
        {{- .Data.text -}}
        {{- end -}}
      EOH
      destination = "/etc/data/configmap.yaml"
    }
