{
 "title": "Finance",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "ISA Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  value,\n  account || '-' || kind as metric\nFROM events\nWHERE\n  $__timeFilter(created_at)\nand\n  kind <> 'sub'\nand\n  account = 'isa'\norder by created_at "
    },
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  value,\n  account || '-' || kind as metric\nFROM events\nWHERE\n  $__timeFilter(created_at)\nand\n  kind <> 'sub'\nand\n  account = 'lisa'\norder by created_at "
    },
    {
     "rawSql": "SELECT\n  created_at as time,\n  value,\n  account || '-subscriptions' as metric\nFROM (SELECT created_at,\n       sum(value) OVER (PARTITION BY account ORDER BY created_at) as value,\n       account,\n       kind\nFROM events\nWHERE\n  kind = 'sub'\nORDER BY created_at) as summed\nWHERE\n  account = 'isa'\n  and\n  kind = 'sub'\n  and\n  $__timeFilter(created_at)\nORDER  BY created_at\n\n"
    },
    {
     "rawSql": "SELECT\n  created_at as time,\n  value,\n  account || '-subscriptions' as metric\nFROM (SELECT created_at,\n       sum(value) OVER (PARTITION BY account ORDER BY created_at) as value,\n       account,\n       kind\nFROM events\nWHERE\n  kind = 'sub'\nORDER BY created_at) as summed\nWHERE\n  account = 'lisa'\n  and\n  kind = 'sub'\n  and\n  $__timeFilter(created_at)\nORDER  BY created_at\n\n"
    }
   ]
  },
  {
   "title": "ISA Allowance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n  value as saved,\n  (time::date - fiscal_year_start::date)::int * ((1.0/365) * 20000)::int as ideal, \n  time \nfrom \n  (\n    select \n      sum(value) over (\n        partition by fiscal_year \n        order by \n          time\n      ) as value, \n      fiscal_year_start, \n      time \n    from \n      (\n        SELECT \n          value, \n          created_at as time, \n          date_part('year', fy.start) as fiscal_year, \n          fy.start as fiscal_year_start \n        FROM \n          events as e \n          inner join fiscal_years as fy on e.created_at between fy.start \n          and fy.end \n        where \n          kind = 'sub' \n        ORDER BY \n          time\n      ) as with_fy\n  ) as cumulative \norder by \n  time\n"
    }
   ]
  },
  {
   "title": "Current Account Balance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  value\nFROM current_balances\nWHERE\n  $__timeFilter(created_at)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Pension Value",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select created_at as time, value from pension_subscriptions\n\n"
    }
   ]
  },
  {
   "title": "ISA Class Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select class_bonds,\nclass_equities,\nclass_property,\nclass_value_stocks,\nclass_unallocated,\ncreated_at as time\n from breakdowns\nWHERE\n  $__timeFilter(created_at)\n  and\n  account = 'isa'\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "LISA Class Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select class_bonds,\nclass_equities,\nclass_property,\nclass_value_stocks,\nclass_unallocated,\ncreated_at as time\n from breakdowns\nWHERE\n  $__timeFilter(created_at)\n  and\n  account = 'lisa'\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Net Worth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "currencyGBP",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select\n-- current\n(select value from current_balances order by created_at desc limit 1) +\n\n-- pension\n(select value from pension_subscriptions order by created_at desc limit 1) +\n\n-- isa\n(SELECT\n  value\nFROM events\nwhere\n  kind = 'value'\nand \n  account = 'isa'\norder by created_at desc\nlimit 1) +\n\n-- lisa\n(SELECT\n  value\nFROM events\nwhere\n  kind = 'value'\nand \n  account = 'lisa'\norder by created_at desc\nlimit 1) as value,\nCURRENT_TIME as time "
    }
   ]
  },
  {
   "title": "Net Worth Breakdown",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 12 },
   "targets": [
    {
     "rawSql": "select * from (select value, 'current' as metric from current_balances order by created_at desc limit 1) as current\nunion\nselect * from (select sum(value) as value, 'pension' as metric from pension_subscriptions) as pension\nunion\nselect * from (\n(SELECT\n  value,\n  'isa' as metric\nFROM events\nwhere\n  kind = 'value'\nand \n  account = 'isa'\norder by created_at desc\nlimit 1)\n) as isa\nunion\nselect * from (\n(SELECT\n  value,\n  'lisa' as metric\nFROM events\nwhere\n  kind = 'value'\nand \n  account = 'lisa'\norder by created_at desc\nlimit 1)\n) as lisa\n\n\n"
    }
   ]
  },
  {
   "title": "Liquid Net Worth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "format": "currencyGBP",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select\n-- current\n(select value from current_balances order by created_at desc limit 1) +\n\n-- isa\n(SELECT\n  value\nFROM events\nwhere\n  kind = 'value'\nand \n  account = 'isa'\norder by created_at desc\nlimit 1) as value,\nCURRENT_TIME as time "
    }
   ]
  },
  {
   "title": "ISA Geo Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select geo_australia_new_zealand,\ngeo_cash_and_equiv_,\ngeo_developed_asia,\ngeo_developed_europe_excl_uk,\ngeo_emerging_asia,\ngeo_emerging_europe,\ngeo_japan,\ngeo_managed_fund,\ngeo_middle_east_africa,\ngeo_non_classified,\ngeo_north_america,\ngeo_property,\ngeo_south_central_america,\ngeo_uk,\ncreated_at as time\n from breakdowns\nWHERE\n  $__timeFilter(created_at)\n  and\n  account = 'isa'\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "LISA Geo Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select geo_australia_new_zealand,\ngeo_cash_and_equiv_,\ngeo_developed_asia,\ngeo_developed_europe_excl_uk,\ngeo_emerging_asia,\ngeo_emerging_europe,\ngeo_japan,\ngeo_managed_fund,\ngeo_middle_east_africa,\ngeo_non_classified,\ngeo_north_america,\ngeo_property,\ngeo_south_central_america,\ngeo_uk,\ncreated_at as time\n from breakdowns\nWHERE\n  $__timeFilter(created_at)\n  and\n  account = 'lisa'\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "ISA Sector  Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select sector_alternative_trading_strategies,\nsector_basic_materials,\nsector_bonds,\nsector_cash_and_equiv_,\nsector_consumer_goods,\nsector_consumer_services,\nsector_financials,\nsector_health_care,\nsector_industrials,\nsector_managed_funds,\nsector_non_classified,\nsector_oil_gas,\nsector_other,\nsector_technology,\nsector_telecommunications,\nsector_utilities,\nsector_unallocated,\ncreated_at as time\n from breakdowns\nWHERE\n  $__timeFilter(created_at)\n  and\n  account = 'isa'\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "LISA Sector  Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select sector_alternative_trading_strategies,\nsector_basic_materials,\nsector_bonds,\nsector_cash_and_equiv_,\nsector_consumer_goods,\nsector_consumer_services,\nsector_financials,\nsector_health_care,\nsector_industrials,\nsector_managed_funds,\nsector_non_classified,\nsector_oil_gas,\nsector_other,\nsector_technology,\nsector_telecommunications,\nsector_utilities,\nsector_unallocated,\ncreated_at as time\n from breakdowns\nWHERE\n  $__timeFilter(created_at)\n  and\n  account = 'lisa'\nORDER BY created_at"
    }
   ]
  }
 ]
}