---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rssmerge
  name: rssmerge
  namespace: rssmerge
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: rssmerge
  sessionAffinity: None
  type: ClusterIP
