global:
  tlsDisable: true
server:
  dataStorage:
    enabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: 25m
    limits:
      memory: 150Mi
      cpu: 400m
  livenessProbe:
    enabled: true
  extraEnvironmentVars:
    GOOGLE_REGION: global
    GOOGLE_PROJECT: charlieegan3-cluster
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/google-application-credentials/key.json
  extraVolumes:
  - type: secret
    name: google-application-credentials
  standalone:
    config: |
      ui = false

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "gcs" {
        bucket     = "charlieegan3-cluster-vault-storage"
      }

      seal "gcpckms" {
        project     = "charlieegan3-cluster"
        region      = "global"
        key_ring    = "vault-key-ring"
        crypto_key  = "vault-server"
      }
