---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clockify
  namespace: clockify
spec:
  selector:
    matchLabels:
      app: clockify
  template:
    metadata:
      labels:
        app: clockify
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "clockify"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-config.json: "secret/clockify/main"
        vault.hashicorp.com/agent-inject-template-config.json: |
          {{- with secret "secret/clockify/main" -}}
          {{- .Data.config -}}
          {{- end -}}
    spec:
      containers:
      - image: "charlieegan3/clockify:92929299652902bbbeaff6e844bf03a1"
        name: clockify
        ports:
        - name: http1
          containerPort: 80
        resources:
          limits:
            cpu: "20m"
            memory: "20Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
        command:
        - sh
        - -c
        - |
          find /vault && \
          mkdir /usr/share/nginx/html/data && \
          cp /vault/secrets/config.json /usr/share/nginx/html/data/ && \
          mkdir -p /var/log/nginx && \
          exec nginx -g "daemon off;"
