---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot
  namespace: boot
spec:
  selector:
    matchLabels:
      app: boot
  template:
    metadata:
      labels:
        app: boot
    spec:
      containers:
      - image: "charlieegan3/boot:arm-765c57982872cabcf503c1bcc3c2ad0abb9e6df2"
        name: boot
        ports:
        - name: http1
          containerPort: 80
        resources:
          limits:
            cpu: "20m"
            memory: "20Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"
